language: r
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: linux
      dist: precise
      sudo: false
cache:
  packages: true
r: bioc-devel
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
